# Generated by Django 5.2.6 on 2026-04-11 12:00

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=transactions.models.get_todays_date)),
                ('transaction_type', models.CharField(choices=[('Ex', 'Expense'), ('In', 'Income')], max_length=2)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
